version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rdb:
    image: redis
    restart: always
    ports:
      - "63790:6379"

  migrate:
    image: migrate/migrate
    volumes:
      - ./schema:/migrations
    command: ["-path", "/migrations", "-database",
              "postgres://postgres:root@db:5432/postgres?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - db

  app:
    container_name: grates
    build: .
    ports:
      - "8001:8001"
    entrypoint: "./wait-for-it.sh db:5432 -- /app/main"
    depends_on:
      - db
      - rdb
    environment:
      - DATABASE_URL=db
      - CONFIG_FILE_NAME=${CONFIG_FILE_NAME}

volumes:
  pgdata:
