version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
  server:
    build: .
    command: ./main
    ports:
      - 8000:8000
#    environment:
#      - PORT=8080
#      - DATABASE_URL=db
    depends_on:
      - db