version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"
  rdb:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - .:/migrations
    command: ["-path", "/migrations", "-database",
              "postgres://postgres:root@localhost:54320/postgres?sslmode=disable"]
    links:
      - db
    depends_on:
      - db

networks:
  new:
#  server:
#    build: .
#    command: ./main
#    ports:
#      - 8000:8000
##    environment:
##      - PORT=8080
##      - DATABASE_URL=db
#    depends_on:
#      - db