version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"
  rdb:
    image: redis
    restart: always
    ports:
      - "63790:6379"
  migrate:
    image: migrate/migrate
    volumes:
      - ./schema:/migrations
    command: ["-path", "/migrations", "-database",
              "postgres://postgres:root@db:5432/postgres?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - db

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rdb
      - migrate
    environment:
      - DATABASE_URL=db

#  server:
#    build: .
#    command: ./main
#    ports:
#      - 8000:8000
##    environment:
##      - PORT=8080
##      - DATABASE_URL=db
#    depends_on:
#      - db