version: '3.8'

services:
  db:
    image: postgres
    restart: always
# TODO
#    env_file: .env https://medium.com/@krishnaregmi/wait-for-it-docker-compose-f0bac30f3357
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"

  rdb:
    image: redis
    restart: always
    ports:
      - "63790:6379"

  migrate:
    image: migrate/migrate
    volumes:
      - ./schema:/migrations
    command: ["-path", "/migrations", "-database",
              "postgres://postgres:root@db:5432/postgres?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - app

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rdb
    environment:
      - DATABASE_URL=db

  app-prod:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rdb
    env_file: .prod.env
