-- DROP TABLE likes_posts;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS posts CASCADE;

DROP TABLE IF EXISTS comments CASCADE;

DROP TABLE IF EXISTS likes_posts CASCADE;

DROP TABLE IF EXISTS auth_emails CASCADE;

DROP TYPE  IF EXISTS gender CASCADE;

DROP TABLE IF EXISTS friend_requests CASCADE;