host: "localhost"
port: ":8000"

db:
  username: "postgres"
  host: "localhost"
  port: "54320"
  dbname: "postgres"
  sslmode: "disable"

rdb:
  addr: "localhost:63790"

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 240m

email:
  smtpHost: "smtp.mail.ru"
  smtpPort: 465
  from: "grates.social@mail.ru"