host: "grates.mgtu.tech"
port: ""

db:
  username: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

rdb:
  addr: "rdb:6379"

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 240m

email:
  smtpHost: "smtp.yandex.ru"
  smtpPort: "465"
  from: "iam@it-yaroslav.ru"