port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "54320"
  dbname: "postgres"
  sslmode: "disable"

rdb:
  addr: "localhost:6379"

auth:
  accessTokenTTL: 10m
  refreshTokenTTL: 30m